
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvkjuqizqetxbgojvtnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2a2p1cWl6cWV0eGJnb2p2dG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjA3MjksImV4cCI6MjA1NjU5NjcyOX0.gVLSgClCuapCFSp4x4xQDtZdwBfKDkPGWF026aJ6MgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storageKey: 'fitnesshub-auth-token'
    },
    // Add global error handler
    global: {
      fetch: async (url, options) => {
        const response = await fetch(url, options);
        
        // Log detailed error information for non-2xx responses
        if (!response.ok && !url.toString().includes('/auth/v1/token')) {
          console.error(`Supabase request failed: ${response.status} ${response.statusText}`, {
            url,
            method: options?.method || 'GET',
          });
        }
        
        return response;
      }
    }
  }
);
